Update AFIT and UMassIT links
umts/dev-training-web pull request #173
Opened 2024-12-04 15:56 UTC by sherson

2024-12-04 18:20 UTC, werebus requested changes

2024-12-04 18:20 UTC, werebus commented on config/qualifications.yml
> +  - '[Security and Safety](https://www.umass.edu/afsystems/basic-page/guides-security-and-safety/330)'
This page contains the following things:
* A link to the "Service Categorizations" page linked to below
* A broken link
* A ton of information on Docusign - unneeded
* A barely-understandably PDF copy of some notes from a presentation that Travis gave in 2012
* A how-to on how to use MS Office document encryption - unneeded

Sounds like we only have one "document" to review at the moment?

2024-12-04 21:46 UTC, werebus approved these changes

2025-03-21 12:06 UTC, dirschn commented
Any particular reason for this not to be merged?

2025-03-21 12:12 UTC, sherson commented
Nope, I just forgot to

2025-03-21 13:13 UTC, merged