Adjustments for 2023 hirings
umts/dev-training-web pull request #30
Opened 2023-03-27 15:56 UTC by benmelz

To sum up the general changes I made:
- Drop no-longer-active programmers from the collaborators file (currently reflects a minimal change, although I would entertain the idea of expanding and/or contracting the list further)
- Reorder/merge/expand the "administrative" items at the start of the list to better reflect what the process will actually look like
- Reorder the "programming" items to reflect the real order in which they'll be completed (straightforward for the tutorials, then I just went from the bottom to the top on the "stack" items)
- Expand/clarify some of the subtasks on the "programming" items

2023-03-29 17:43 UTC, werebus requested changes

2023-03-29 17:43 UTC, werebus commented on config/collaborators.yml
>  - sherson
I think you can add @dirschn

2023-03-29 18:54 UTC, benmelz commented on config/qualifications.yml
> +  free using your UMass account and watch [these videos](https://learning.oreilly.com/videos/ruby-fundamentals/300000006A0154),
I couldn't find said content, so I changed it to offer Koans first and codeacademy second (I'd like them to do the Koans if they can, and if it's a little too advanced, then codeacademy's spoon-fed version)

2023-04-03 14:26 UTC, werebus approved these changes

2023-04-03 14:36 UTC, merged